#Course: Deep Learning
#Program: MBA Tech AI
#Sem: V
# Academic Year: 2023-24
# Instructor: Dr.Radhika Chapaneri
# Experiment No: 2

#Roll No: R046
#Name: Tungishsanjay Sankar
#Batch : B2
#Date of Experiment: 10-08-2023
#Title: Feed Forward Nueral Networks





In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Iris.csv")
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df_1 = pd.get_dummies(df, columns = ['Species'])

In [ ]:
df_1.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0            5.1           3.5            1.4           0.2   
1            4.9           3.0            1.4           0.2   
2            4.7           3.2            1.3           0.2   
3            4.6           3.1            1.5           0.2   
4            5.0           3.6            1.4           0.2   

   Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica  
0                    1                        0                       0  
1                    1                        0                       0  
2                    1                        0                       0  
3                    1                        0                       0  
4                    1                        0                       0

In [ ]:
df.drop("Species", axis=1, inplace=True)

In [ ]:
df.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [ ]:
df_scaled = std_scaler.fit_transform(df)

In [ ]:
df_scaled.head()

AttributeError: ignored

In [ ]:
df_transformed = pd.DataFrame(df_scaled, columns = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])

In [ ]:
df_transformed.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.900681      1.032057      -1.341272     -1.312977
1      -1.143017     -0.124958      -1.341272     -1.312977
2      -1.385353      0.337848      -1.398138     -1.312977
3      -1.506521      0.106445      -1.284407     -1.312977
4      -1.021849      1.263460      -1.341272     -1.312977

In [ ]:
df_1.drop(columns=["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"], inplace=True)

In [ ]:
df_1

Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                      1                        0                       0
1                      1                        0                       0
2                      1                        0                       0
3                      1                        0                       0
4                      1                        0                       0
..                   ...                      ...                     ...
145                    0                        0                       1
146                    0                        0                       1
147                    0                        0                       1
148                    0                        0                       1
149                    0                        0                       1

[150 rows x 3 columns]

In [ ]:
Iris_df=pd.concat([df_transformed,df_1],axis=1)

In [ ]:
Iris_df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      -0.900681      1.032057      -1.341272     -1.312977   
1      -1.143017     -0.124958      -1.341272     -1.312977   
2      -1.385353      0.337848      -1.398138     -1.312977   
3      -1.506521      0.106445      -1.284407     -1.312977   
4      -1.021849      1.263460      -1.341272     -1.312977   

   Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica  
0                    1                        0                       0  
1                    1                        0                       0  
2                    1                        0                       0  
3                    1                        0                       0  
4                    1                        0                       0

In [ ]:
input = Iris_df.iloc[:,0:4]

In [ ]:
input.shape

(150, 4)

In [ ]:
np.random.seed(42)
w_i_h1=np.random.rand(4,1)
w_i_h2=np.random.rand(4,1)
w_h_o1=np.random.rand(2,1)
w_h_o2=np.random.rand(2,1)
w_h_o3=np.random.rand(2,1)
bias1=np.random.rand(1)
bias2=np.random.rand(1)

In [ ]:
print(w_i_h1)
print("/n")
print(w_i_h2)
print("/n")
print(w_h_o1)
print("/n")
print(w_h_o2)
print("/n")
print(w_h_o3)
print("/n")
print(bias1)
print("/n")
print(bias2)

[[0.37454012]
 [0.95071431]
 [0.73199394]
 [0.59865848]]
/n
[[0.15601864]
 [0.15599452]
 [0.05808361]
 [0.86617615]]
/n
[[0.60111501]
 [0.70807258]]
/n
[[0.02058449]
 [0.96990985]]
/n
[[0.83244264]
 [0.21233911]]
/n
[0.18182497]
/n
[0.18340451]


In [ ]:
def sigmoid(x):
  return 1/(1+ np.exp(-x))

In [ ]:
# Feedforward Step1- input to hidden layer
Z2_1=np.dot(input,w_i_h1) + bias1
Z2_2=np.dot(input,w_i_h2) + bias2

In [ ]:
print(Z2_1)

[[-0.94215263]
 [-2.13290763]
 [-1.82530122]
 [-2.00743086]
 [-0.76753675]
 [ 0.35627737]
 [-1.31035447]
 [-1.16590762]
 [-2.57981689]
 [-1.94999158]
 [-0.32438437]
 [-1.21504672]
 [-2.25699727]
 [-2.60878447]
 [ 0.39226282]
 [ 1.5091639 ]
 [ 0.18977596]
 [-0.86344522]
 [ 0.19371853]
 [-0.16182554]
 [-0.901128  ]
 [-0.30311624]
 [-1.11556707]
 [-1.02115057]
 [-1.09017067]
 [-2.0042747 ]
 [-0.96686745]
 [-0.85514505]
 [-1.11676851]
 [-1.70042517]
 [-1.87504105]
 [-0.82696388]
 [ 0.3861362 ]
 [ 0.77936305]
 [-1.94999158]
 [-1.73077989]
 [-0.80224907]
 [-1.94999158]
 [-2.40144413]
 [-1.12052539]
 [-0.9504528 ]
 [-3.81734126]
 [-1.96144791]
 [-0.58945452]
 [ 0.08338327]
 [-2.09958245]
 [-0.1989076 ]
 [-1.8290581 ]
 [-0.3697666 ]
 [-1.42753108]
 [ 1.57824087]
 [ 1.30140421]
 [ 1.47481864]
 [-1.45256041]
 [ 0.50841935]
 [-0.05367865]
 [ 1.6379782 ]
 [-2.03235535]
 [ 0.61638487]
 [-0.6716326 ]
 [-2.78371486]
 [ 0.50962079]
 [-1.6817696 ]
 [ 0.50980648]
 [-0.25369093]
 [ 1.09722002]
 [ 0.49835

In [ ]:
#Feedforward step2
h2_1 = sigmoid(Z2_1)
h2_2 = sigmoid(Z2_2)

In [ ]:
h2_1.shape

(150, 1)

In [ ]:
# Each output neuron gets input from both hidden layers
h2=np.append(h2_1,h2_2,axis=1)

In [ ]:
h2

array([[0.28046573, 0.26672584],
       [0.10593928, 0.22625228],
       [0.13879898, 0.23174005],
       [0.11842493, 0.22323584],
       [0.3170122 , 0.27010199],
       [0.58813899, 0.36065366],
       [0.21242753, 0.26346438],
       [0.2375955 , 0.25673706],
       [0.07044872, 0.20420536],
       [0.12455428, 0.21348027],
       [0.41960762, 0.29336704],
       [0.22880931, 0.25020799],
       [0.0947476 , 0.20385402],
       [0.0685752 , 0.18742803],
       [0.59682731, 0.33068575],
       [0.81893726, 0.41534004],
       [0.54730211, 0.35761287],
       [0.29662004, 0.28958106],
       [0.54827875, 0.33943989],
       [0.45963167, 0.31306608],
       [0.28881875, 0.27273829],
       [0.42479587, 0.33003148],
       [0.24683447, 0.25295103],
       [0.26480334, 0.32476731],
       [0.25158614, 0.25207153],
       [0.11875484, 0.23074935],
       [0.27550533, 0.30323567],
       [0.29835468, 0.27109167],
       [0.24661118, 0.26337667],
       [0.15440974, 0.23350889],
       [0.

In [ ]:
h2.shape

(150, 2)

In [ ]:
Z3_1 = np.dot(h2,w_h_o1)
Z3_2 = np.dot(h2,w_h_o2)
Z3_3 = np.dot(h2,w_h_o3)

In [ ]:
Z3_1.shape

(150, 1)

In [ ]:
O1 = sigmoid(Z3_1)
O2 = sigmoid(Z3_2)
O3 = sigmoid(Z3_3)

In [ ]:
O1.shape

(150, 1)

In [ ]:
O2.shape

(150, 1)

In [ ]:
O3.shape

(150, 1)

In [ ]:
t1=np.array(Iris_df.iloc[:,4])

In [ ]:
t1.shape

(150,)

In [ ]:
t1=t1.reshape((-1,1))
t1.shape

(150, 1)

In [ ]:
t2=np.array(Iris_df.iloc[:,5])
t2=t2.reshape((-1,1))
t2.shape

(150, 1)

In [ ]:
t3=np.array(Iris_df.iloc[:,6])
t3=t3.reshape((-1,1))
t3.shape

(150, 1)

In [ ]:
e1=t1-O1
e2=t2-O2
e3=t3-O3

In [ ]:
e1.shape

(150, 1)

In [ ]:
e2.shape

(150, 1)

In [ ]:
e3.shape

(150, 1)

In [ ]:
error=np.multiply(e1,e1)+np.multiply(e2,e2)+np.multiply(e3,e3)

In [ ]:
error_total=np.sum(error)

In [ ]:
error_total

144.83471642466847